plugins {
	id 'application'
	id 'com.gradleup.shadow'
}

dependencies {
	implementation project(':enigma')
	implementation 'net.sf.jopt-simple:jopt-simple:6.0-alpha-3'
	implementation 'io.modelcontextprotocol.sdk:mcp:2.0.0'
	implementation 'org.eclipse.jetty:jetty-servlet:11.0.24'

	// Source: https://mvnrepository.com/artifact/com.github.victools/jsonschema-generator
	implementation("com.github.victools:jsonschema-generator:5.0.0")
	// Source: https://mvnrepository.com/artifact/com.github.victools/jsonschema-module-jackson
	implementation("com.github.victools:jsonschema-module-jackson:5.0.0")

	testImplementation 'com.google.jimfs:jimfs:1.2'
}

def generateTestTargetJarTask = tasks.register("generateTestTargetJar", Jar) {
	def enigmaProject = project(":enigma")

	dependsOn(enigmaProject.tasks.named("test"))

	it.from(enigmaProject.sourceSets.test.output) {
		include "cuchaz/enigma/inputs/**/*.class"
	}

	archiveFileName = 'test-inputs.jar'
	destinationDirectory = file('build/test-inputs')
}

test.dependsOn(generateTestTargetJarTask)

application {
	mainClass = 'cuchaz.enigma.mcp.EnigmaMcpMain'
}

jar.manifest.attributes 'Main-Class': application.mainClass.get()
